### ISSUE TITLE
[NEW REQUEST]

### ISSUE THREAD

**Issue by erulabs** [kubesail/templates#95]
**Website**: https://joplinapp.org/
**GitHub**: https://github.com/laurent22/joplin/
**Docker Image**: https://hub.docker.com/r/florider89/joplin-server
**Has arm64 image**: ^ image is unofficial, but seems pretty widely used, has ARM64
---
**Other Useful Information**: (Other Links, guides, etc)

**Comment by DrMxrcy** [comment]
#91 Duplicate Request
